### ISSUE TITLE
Link to source in feed description?

### ISSUE THREAD

**Issue by poVoq** [wbernest/mattermost-plugin-rssfeed#10]
Would be awesome if the setting to add a description of the source would not only write it, but also add a hyperlink so that people can easily navigate to the source.

Thanks!

**Comment by wbernest** [comment]
I am already including the link in the post.  It sounds like the rss feed you are using may not be properly constructing the content.  Send me the link and I will check it out.

**Comment by poVoq** [comment]
I am just reposting it from an aggregated feed from Hubzilla. Here are the links:
https://social.freegamedev.net/channel/planet
RSS feed:
https://social.freegamedev.net/feed/planet

**Comment by wbernest** [comment]
I added some links for the atom feeds but they may or may not be what people are looking for.

https://github.com/wbernest/mattermost-plugin-rssfeed/releases/tag/v0.0.6

**Comment by poVoq** [comment]
Working nicely, thanks!
