### ISSUE TITLE
Create necessary bot instead of using existing user

### ISSUE THREAD

**Issue by zebastiane** [wbernest/mattermost-plugin-rssfeed#13]
Hi,

Thank you for this plugin.

Since Mattermost 5.10 it's possible de create a [`bot`](https://developers.mattermost.com/extend/plugins/server/reference/#API.CreateBot) with the API.
The [remind plugin](https://github.com/scottleedavis/mattermost-plugin-remind) does this and it simplifies installation and configuration of the plugin.

Would it be possible to implement this API?
Sure the drawback would be to require Mattermost 5.10 or greater.

**Comment by wbernest** [comment]
Got it.

https://github.com/wbernest/mattermost-plugin-rssfeed/releases/tag/v0.1.0

**Comment by zebastiane** [comment]
It works, thank you!
