### ISSUE TITLE
Prevent message flood for newly subscribed feeds

### ISSUE THREAD

**Issue by giannello** [wbernest/mattermost-plugin-rssfeed#20]
After subscribing to a new feed, the first update run results in _all_ the feed entries to be posted as messages. For some feeds, this results in lots of messages flooding the channel.

A possible solution would be to fetch the feeds silently as soon as they are added.

**Comment by felibb** [comment]
Adding my voice here. Was able to prevent flooding with my own feed by adjusting the feed setting for the number of most recent posts, but that is impossible for public feeds.

I suggest a setting e.g. to show only N recent posts on subscribing.

**Comment by bbodenmiller** [comment]
I agree this would be helpful. Subscribing and then getting a lot of messages isn't ideal.

**Comment by heartbleeded** [comment]
Yes there should have an option showing that only N recent posts on feeds.

**Comment by frezbo** [comment]
Is this something that can be addressed, I'm happy to contribute, can someone please point me where to start? i added my RSS subscriptions and the message flood is still going on.

**Comment by wbernest** [comment]
You can start here, I think.  
https://github.com/wbernest/mattermost-plugin-rssfeed/blob/873bf82827138b8ab841fbf5c30767cd1d5de1e4/server/plugin.go#L101
