### ISSUE TITLE
no trigger /feed available

### ISSUE THREAD

**Issue by amaxilat** [wbernest/mattermost-plugin-rssfeed#3]
I am using Mattermost v4.10.0 on Docker Swarm and although I have installed and activated the plugin when I try to run /feed on the channel of my choice I get the following: 

> Command with a trigger of 'feed' not found. To send a message beginning with "/", try adding an empty space at the beginning of the message.

**Comment by wbernest** [comment]
You will need to change your logging to debug in mattermost then disable and enable the plugin from the mattermost cli.  If there are any start up issues they should print out there and if they don't you can check the logs/mattermost.log file | grep 'rssfeed' to get rssfeed specific errors.

**Comment by icedream** [comment]
In my case the error message only says that a connection got closed. Presumably, this is the connection between the Mattermost server and the plugin?

**Comment by icedream** [comment]
It seems like at some point the plugin crashes while processing an Atom feed. After that the `/feed` trigger becomes unavailable and the plugin has to be disabled, then re-enabled.

```
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      panic: runtime error: invalid memory address or nil pointer dereference {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9e3cd0]  {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34              {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      goroutine 16 [running]: {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      main.(*RSSFeedPlugin).processAtomSubscription(0xc0002000f0, 0xc0001ce750, 0xc0002ee240, 0xc000249200)   {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34              /go/src/github.com/wbernest/mattermost-plugin-rssfeed/server/plugin.go:181 +0x1b0       {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      main.(*RSSFeedPlugin).processSubscription(0xc0002000f0, 0xc0001ce750, 0x0, 0x0) {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34              /go/src/github.com/wbernest/mattermost-plugin-rssfeed/server/plugin.go:114 +0x144       {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      main.(*RSSFeedPlugin).processHeartBeat(0xc0002000f0, 0x1e, 0x0) {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34              /go/src/github.com/wbernest/mattermost-plugin-rssfeed/server/plugin.go:78 +0xcf {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      main.(*RSSFeedPlugin).setupHeartBeat(0xc0002000f0)      {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34              /go/src/github.com/wbernest/mattermost-plugin-rssfeed/server/plugin.go:62 +0x82 {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34      created by main.(*RSSFeedPlugin).OnActivate     {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.024+0200 debug   plugin/hclog_adapter.go:34              /go/src/github.com/wbernest/mattermost-plugin-rssfeed/server/activate.go:23 +0x241      {"plugin_id": "rssfeed"}
<redacted service name>    | 2019-06-03T10:53:03.045+0200 debug   plugin/hclog_adapter.go:32      plugin process exited   {"plugin_id": "rssfeed", "wrapped_extras": "pathplugins/rssfeed/server/dist/plugin-linux-amd64pid497errorexit status 2"}
```

**Comment by wbernest** [comment]
It is probably the version of Mattermost you are using.  Upgrade to 5.6 to use the versions of my plugin before 0.1 or upgrade to 5.10 to use 0.1.

**Comment by icedream** [comment]
Mattermost was already at the newest stable version (5.11.0) at the point where the log was written.

**Comment by wbernest** [comment]
No, 5.11 should be fine, Mattermost APIs are backwards compatible.

If the plugin is crashing on an Atom feed, then the chances are that the atom feed either does not match the atom feed standard or it does not match the format I am using to spit out data.

**Comment by icedream** [comment]
I can only guess that one of the several feeds that the bot is subscribed to is indeed malformed or at least skips some required fields. I also noticed that after this crash the feeds stop updating altogether, as such the bot no longer posts feed updates to Mattermost and has to be reloaded to do so again. This should probably be handled in form of a log message (warning?).

**Comment by icedream** [comment]
Here is an example for an Atom feed that would cause the crash without the change that I just implemented on my fork: https://xkcd.com/atom.xml. All feed items have a `<summary>` which is somehow not used to fill in the `Content` field in the Go code, as such that field is `nil` which would make any access cause a panic.

**Comment by wbernest** [comment]
Ok, go ahead and do a pull request and I will pull in your changes.

**Comment by icedream** [comment]
Before I can make the pull request I still have to check how to restore the preview/content that is now missing, see this: 
![image](https://user-images.githubusercontent.com/807772/59908575-01abcc80-940e-11e9-95a5-b45b8ee17a71.png)

**Comment by icedream** [comment]
I have marked the PR that just prevents the plugin server from crashing as ready to merge. No fix or measurements for the missing content item included yet.
