### ISSUE TITLE
You have include a mortgage payment document in the repo

### ISSUE THREAD

**Issue by trobol** [wbernest/mattermost-plugin-rssfeed#36]
Its in the images folder. You might want to [remove it from the history](https://myopswork.com/how-remove-files-completely-from-git-repository-history-47ed3e0c4c35)

**Comment by wbernest** [comment]
Thanks!

**Comment by trobol** [comment]
The file still exists in the repo history. You should use filter it from the entire history.

**Comment by wbernest** [comment]
Thanks again.  That was kind of a pain in the ass to remove .....

**Comment by trobol** [comment]
https://xkcd.com/1597/
