### ISSUE TITLE
How can I subscribe some urls once?

### ISSUE THREAD

**Issue by lindexi** [wbernest/mattermost-plugin-rssfeed#4]
Thx for the good app.

I find many urls to subscribe to. How can I subscribe to some urls once?

**Comment by wbernest** [comment]
To use the plugin, navigate to the channel you want subscribed and use the following commands:

/feed help                  // to see the help menu
/feed subscribe <url>       // to subscribe the channel to an rss feed
/feed unsubscribe <url>     // to unsubscribe the channel from an rss feed
/feed list                  // to list the feeds the channel is subscribed to

**Comment by lindexi** [comment]
@wbernest Thanks. But I want to feed some urls once replace than to subscribe the channel to an rss feed.

Can I  subscribe the channel to some rss feed by one command?

**Comment by wbernest** [comment]
You can subscribe a channel to as many rss feeds as you want.  Just keep typing /feed subscribe <url>.

**Comment by lindexi** [comment]
Do I use the command?

    /feed subscribe url1 url2 url3

**Comment by wbernest** [comment]
No 

/feed subscribe url1 
/feed subscribe url2  
/feed subscribe url3

**Comment by lindexi** [comment]
Seem failing

![image](https://user-images.githubusercontent.com/16054566/56775761-1ea39500-67fb-11e9-8ab8-80b1a702eb7c.png)

![image](https://user-images.githubusercontent.com/16054566/56775770-26633980-67fb-11e9-8a5c-cec65a217785.png)

**Comment by tgly307** [comment]
@lindexi url is invalid, use this http://feed.cnblogs.com/blog/u/360071/rss

**Comment by lindexi** [comment]
@tgly307 Can you use a command with multiple urls?

**Comment by lindexi** [comment]
It will be failed when I input multiple urls and it will succeed when I input one urls

![image](https://user-images.githubusercontent.com/16054566/56780493-1a36a680-6812-11e9-9666-c6d8b90c4859.png)

**Comment by tgly307** [comment]
@lindexi multiple urls failed. this plugin is not support this

**Comment by wbernest** [comment]
It allows me to add the multiple urls.  Make sure you are submitting the form between each command, not running the commands concurrently in a form.  

Also ensure your rss feed is version 2.0.

![Capture](https://user-images.githubusercontent.com/11617314/56811402-9dea9600-6806-11e9-9d49-12d23e713250.JPG)

**Comment by wbernest** [comment]
Also, after digging around it looks like the rss encoding needs to be in UTF-8.

**Comment by wbernest** [comment]
I changed the parser so non UTF-8 encoded xml works now.

**Comment by lindexi** [comment]
Thanks
