### ISSUE TITLE
How to tell which feed is throwing "invalid feed format"?

### ISSUE THREAD

**Issue by doncoffin** [wbernest/mattermost-plugin-rssfeed#45]
I've recently migrated several tens of feeds from Slack to Mattermost, and the Mattermost rssfeed plugin is throwing a lot of "invalid feed format" errors. Some of the feeds do appear to be missing. However, I have no easy way to determine which feeds are actually failing.

Would it be possible to log the URL of the failed feed?

Ultimately I'd like to figure out why so many of the feeds seem to be failing since moving to Mattermost.

Thanks!

**Comment by frezbo** [comment]
@doncoffin I've had the same issue after migrating a lot of feeds to MM. https://github.com/wbernest/mattermost-plugin-rssfeed/pull/46 I've put in this PR that should fix this issue.
