### ISSUE TITLE
Public posting

### ISSUE THREAD

**Issue by mathiasblc** [wbernest/mattermost-plugin-rssfeed#5]
Hello,

Many thanks for your work on this plugin. Can you please make it possible to post in "public" mode? I mean not posting in "Only visible to you", so everyone in the channel can see it?

🙏🏻

**Comment by wbernest** [comment]
This is already how the plugin works.

Posts from rss feed items are done publicly.

Posts returned to you when you type a /feed command are done as ephemerally and show privately.

**Comment by mathiasblc** [comment]
Ah alright, thanks for your answer and sorry for the noise.
