### ISSUE TITLE
feed items not overwriting user

### ISSUE THREAD

**Issue by poVoq** [wbernest/mattermost-plugin-rssfeed#9]
Nice project, thanks for creating it!

Overall it is working fine, but other than the command responses (/feed list etc.), the actual rss feed post are done as the user that I selected in the settings.

Maybe I am overlooking something as I am new to Mattermost, but I think I have the two setting to allow overwriting the avatar and the username set in the system console.

**Comment by wbernest** [comment]
Yes, I am aware of this and it bothers me as well.  I have worked on it multiple times and I still have not been able to figure out how to fix it.

**Comment by wbernest** [comment]
Figured it out!

https://github.com/wbernest/mattermost-plugin-rssfeed/releases/tag/v0.0.6

**Comment by poVoq** [comment]
Works great now. Thanks!
